version: '2'
services:
    uplus-app:
        image: uplus
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://uplus-postgresql:5432/uplus
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    uplus-postgresql:
        extends:
            file: postgresql.yml
            service: uplus-postgresql
